import { Hono } from "hono";
import auth from "./auth.route";
import user from "./user.route";
import notif from "./notification.route";
import files from "./files.route";
import companies from "./companies.route";
import referenceDocs from "./reference-documents.route";
import criteria from "./acceptance-criteria.route";
import processTemplates from "./process-templates.route";
import processTemplateCriteria from "./process-template-criteria.route";
import processDependencies from "./process-dependencies.route";
import tanks from "./tanks.route";
import tankProcesses from "./tank-processes.route";
import inspectionRequests from "./inspection-requests.route";
import findings from "./findings.route";
import dailyReports from "./daily-reports.route";
import testRecordsNested from "./test-records.route";
import testRecordsFlat from "./test-records-flat.route";
import radiographyNested from "./radiography.route";
import radiographyFlat from "./radiography-flat.route";
import radiographyJoints from "./radiography-joints.route";
import dashboard from "./dashboard.route";
import reports from "./reports.route";

const v1 = new Hono();

v1.route("/auth", auth);
v1.route("/users", user);
v1.route("/notifications", notif);
v1.route("/files", files);
v1.route("/companies", companies);
v1.route("/reference-documents", referenceDocs);
v1.route("/acceptance-criteria", criteria);
v1.route("/process-templates", processTemplates);
v1.route("/process-template-criteria", processTemplateCriteria);
v1.route("/process-dependencies", processDependencies);
v1.route("/tanks", tanks);
v1.route("/processes", tankProcesses);
v1.route("/processes", testRecordsNested);
v1.route("/processes", radiographyNested);
v1.route("/inspection-requests", inspectionRequests);
v1.route("/findings", findings);
v1.route("/daily-reports", dailyReports);
v1.route("/test-records", testRecordsFlat);
v1.route("/radiography-tests", radiographyFlat);
v1.route("/radiography-joints", radiographyJoints);
v1.route("/dashboard", dashboard);
v1.route("/reports", reports);

export default v1;
