version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: social_media
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
      - .env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pixel.rule=Host(`pixel-api.ahmadfiqrioemry.com`)"
      - "traefik.http.services.pixel.loadbalancer.server.port=5000"
      - "traefik.http.routers.pixel.entrypoints=websecure"
      - "traefik.http.routers.pixel.tls.certresolver=cloudflare"

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - shared-net

networks:
  shared-net:
    external: true
