services:
  app:
    build: .
    container_name: social_media
    restart: unless-stopped

    env_file:
      - .env.production

    expose:
      - "${APP_PORT}"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=cloudflare"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"

      # Fix WebSocket
      - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.Connection=keep-alive, Upgrade"
      - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.routers.${APP_NAME}.middlewares=ws-headers"

    networks:
      - shared-net

networks:
  shared-net:
    external: true
