const errorMessages = {
  userCreationFailed: "Failed to create user",
  internalServerError: "Internal Server Error",
  notFound: "Resource Not Found",
  unauthorized: "Unauthorized",
  forbidden: "Forbidden Access",
  badRequest: "Bad Request",
  tooManyRequests: "Too Many Requests",
  invalidToken: "Invalid or Expired Token",
  accountInactive: "Account is inactive",
  accountBanned: "Account banned",
  sessionRevoked: "Session revoked",
  emailExists: "Email already exists",
  invalidCredentials: "Invalid email or password",
  invalidCurrentPassword: "Invalid current password",
  userNotFound: "User not found",
  emailAlreadyVerified: "Email is already verified",
  sessionNotFound: "Session not found",
  emailNotVerified: "Email not verified",
  errorFileTooLarge: "File size exceeds the limit",
  invalidFileType: "File type is not allowed",
  fileNotFound: "File not found",
  fileIdRequired: "File ID is required",
  invalidRecord: "Invalid file record",
  invalidFileRecord: "Invalid file record for post",
  postNotFound: "Post not found",
  alreadyLikedPost: "You have already liked this post",
  alreadyUnlikedPost: "You have already unliked this post",
};

export default errorMessages;
