const errorCodes = {
  userCreationFailed: "USER_CREATION_FAILED",
  internalServerError: "INTERNAL_SERVER_ERROR",
  notFound: "NOT_FOUND",
  unauthorized: "UNAUTHORIZED",
  forbidden: "FORBIDDEN",
  badRequest: "BAD_REQUEST",
  tooManyRequests: "TOO_MANY_REQUESTS",
  invalidToken: "INVALID_TOKEN",
  accountDisabled: "ACCOUNT_DISABLED",
  sessionRevoked: "SESSION_REVOKED",
  emailExists: "EMAIL_EXISTS",
  invalidCredentials: "INVALID_CREDENTIALS",
  userNotFound: "USER_NOT_FOUND",
  emailAlreadyVerified: "EMAIL_ALREADY_VERIFIED",
  invalidCurrentPassword: "INVALID_CURRENT_PASSWORD",
  sessionNotFound: "SESSION_NOT_FOUND",
  accountBanned: "ACCOUNT_BANNED",
  emailNotVerified: "EMAIL_NOT_VERIFIED",
  fileNotFound: "FILE_NOT_FOUND",
  fileTooLarge: "FILE_TOO_LARGE",
  invalidFileType: "INVALID_FILE_TYPE",
  invalidFileRecord: "INVALID_FILE_RECORD",
  validationError: "VALIDATION_ERROR",
  postNotFound: "POST_NOT_FOUND",
  alreadyLikedPost: "ALREADY_LIKED_POST",
  alreadyUnlikedPost: "ALREADY_UNLIKED_POST",
};

export default errorCodes;
