import { RoleEnum } from "generated/prisma";

export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard.read",

  USER_CREATE: "user.create",
  USER_READ: "user.read",
  USER_UPDATE: "user.update",
  USER_DELETE: "user.delete",

  TANK_CREATE: "tank.create",
  TANK_READ: "tank.read",
  TANK_UPDATE: "tank.update",
  TANK_DELETE: "tank.delete",

  PROCESS_READ: "process.read",
  PROCESS_UPDATE: "process.update",

  DAILY_REPORT_CREATE: "daily_report.create",
  DAILY_REPORT_READ: "daily_report.read",
  DAILY_REPORT_UPDATE: "daily_report.update",
  DAILY_REPORT_DELETE: "daily_report.delete",
  DAILY_REPORT_PRINT: "daily_report.print",

  FINDING_CREATE: "finding.create",
  FINDING_READ: "finding.read",
  FINDING_UPDATE: "finding.update",
  FINDING_CLOSE: "finding.close",
  FINDING_DELETE: "finding.delete",

  CHECKLIST_READ: "checklist.read",
  CHECKLIST_UPDATE: "checklist.update",

  INSPECTION_REQUEST_CREATE: "inspection_request.create",
  INSPECTION_REQUEST_READ: "inspection_request.read",
  INSPECTION_REQUEST_REVIEW: "inspection_request.review",
  INSPECTION_REQUEST_UPDATE: "inspection_request.update",

  TEST_RECORD_CREATE: "test_record.create",
  TEST_RECORD_READ: "test_record.read",
  TEST_RECORD_UPDATE: "test_record.update",
  TEST_RECORD_COMPLETE: "test_record.complete",
  TEST_RECORD_DELETE: "test_record.delete",

  FILE_UPLOAD: "file.upload",
  FILE_READ: "file.read",

  REPORT_PRINT: "report.print",

  MASTER_PROCESS_CREATE: "master_process.create",
  MASTER_PROCESS_READ: "master_process.read",
  MASTER_PROCESS_UPDATE: "master_process.update",
  MASTER_PROCESS_DELETE: "master_process.delete",

  ACCEPTANCE_CRITERIA_CREATE: "acceptance_criteria.create",
  ACCEPTANCE_CRITERIA_READ: "acceptance_criteria.read",
  ACCEPTANCE_CRITERIA_UPDATE: "acceptance_criteria.update",
  ACCEPTANCE_CRITERIA_DELETE: "acceptance_criteria.delete",

  REFERENCE_DOCUMENT_CREATE: "reference_document.create",
  REFERENCE_DOCUMENT_READ: "reference_document.read",
  REFERENCE_DOCUMENT_UPDATE: "reference_document.update",
  REFERENCE_DOCUMENT_DELETE: "reference_document.delete",

  COMPANY_CREATE: "company.create",
  COMPANY_READ: "company.read",
  COMPANY_UPDATE: "company.update",
  COMPANY_DELETE: "company.delete",

  PROCESS_DEPENDENCY_CREATE: "process_dependency.create",
  PROCESS_DEPENDENCY_READ: "process_dependency.read",
  PROCESS_DEPENDENCY_UPDATE: "process_dependency.update",
  PROCESS_DEPENDENCY_DELETE: "process_dependency.delete",

  NOTIFICATION_CREATE: "notification.create",
  NOTIFICATION_READ: "notification.read",
  NOTIFICATION_UPDATE: "notification.update",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const USER_PERMISSIONS: Permission[] = [
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.USER_READ,
  PERMISSIONS.TANK_READ,
  PERMISSIONS.PROCESS_READ,
  PERMISSIONS.CHECKLIST_READ,
  PERMISSIONS.FINDING_READ,
  PERMISSIONS.DAILY_REPORT_READ,
  PERMISSIONS.INSPECTION_REQUEST_READ,
  PERMISSIONS.INSPECTION_REQUEST_REVIEW,
  PERMISSIONS.TEST_RECORD_READ,
  PERMISSIONS.MASTER_PROCESS_READ,
  PERMISSIONS.ACCEPTANCE_CRITERIA_READ,
  PERMISSIONS.REFERENCE_DOCUMENT_READ,
  PERMISSIONS.COMPANY_READ,
  PERMISSIONS.PROCESS_DEPENDENCY_READ,
  PERMISSIONS.FILE_READ,
  PERMISSIONS.NOTIFICATION_READ,
  PERMISSIONS.NOTIFICATION_UPDATE,
  PERMISSIONS.REPORT_PRINT,
];

const INSPECTOR_PERMISSIONS: Permission[] = [
  ...USER_PERMISSIONS,
  PERMISSIONS.FILE_UPLOAD,
  PERMISSIONS.TANK_CREATE,
  PERMISSIONS.TANK_UPDATE,
  PERMISSIONS.PROCESS_UPDATE,
  PERMISSIONS.CHECKLIST_UPDATE,
  PERMISSIONS.FINDING_CREATE,
  PERMISSIONS.FINDING_UPDATE,
  PERMISSIONS.DAILY_REPORT_CREATE,
  PERMISSIONS.DAILY_REPORT_UPDATE,
  PERMISSIONS.DAILY_REPORT_DELETE,
  PERMISSIONS.DAILY_REPORT_PRINT,
  PERMISSIONS.INSPECTION_REQUEST_CREATE,
  PERMISSIONS.INSPECTION_REQUEST_UPDATE,
  PERMISSIONS.TEST_RECORD_CREATE,
  PERMISSIONS.TEST_RECORD_UPDATE,
  PERMISSIONS.TEST_RECORD_COMPLETE,
];

const ADMIN_PERMISSIONS: Permission[] = [
  ...INSPECTOR_PERMISSIONS,
  PERMISSIONS.USER_CREATE,
  PERMISSIONS.USER_UPDATE,
  PERMISSIONS.USER_DELETE,
  PERMISSIONS.TANK_DELETE,
  PERMISSIONS.FINDING_CLOSE,
  PERMISSIONS.FINDING_DELETE,
  PERMISSIONS.TEST_RECORD_DELETE,
  PERMISSIONS.MASTER_PROCESS_CREATE,
  PERMISSIONS.MASTER_PROCESS_UPDATE,
  PERMISSIONS.MASTER_PROCESS_DELETE,
  PERMISSIONS.ACCEPTANCE_CRITERIA_CREATE,
  PERMISSIONS.ACCEPTANCE_CRITERIA_UPDATE,
  PERMISSIONS.ACCEPTANCE_CRITERIA_DELETE,
  PERMISSIONS.REFERENCE_DOCUMENT_CREATE,
  PERMISSIONS.REFERENCE_DOCUMENT_UPDATE,
  PERMISSIONS.REFERENCE_DOCUMENT_DELETE,
  PERMISSIONS.COMPANY_CREATE,
  PERMISSIONS.COMPANY_UPDATE,
  PERMISSIONS.COMPANY_DELETE,
  PERMISSIONS.PROCESS_DEPENDENCY_CREATE,
  PERMISSIONS.PROCESS_DEPENDENCY_READ,
  PERMISSIONS.PROCESS_DEPENDENCY_UPDATE,
  PERMISSIONS.PROCESS_DEPENDENCY_DELETE,
  PERMISSIONS.NOTIFICATION_CREATE,
];

export const ROLE_PERMISSIONS: Record<RoleEnum, Permission[] | ["*"]> = {
  [RoleEnum.USER]: USER_PERMISSIONS,
  [RoleEnum.INSPECTOR]: INSPECTOR_PERMISSIONS,
  [RoleEnum.ADMIN]: ADMIN_PERMISSIONS,
  [RoleEnum.SUPER_ADMIN]: ["*"],
};

export function getPermissionsForRole(role: RoleEnum): Permission[] | ["*"] {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(role: RoleEnum, permission: Permission): boolean {
  const perms = getPermissionsForRole(role);
  if (perms[0] === "*") return true;
  return (perms as Permission[]).includes(permission);
}
