const successMessages = {
  // auth
  registerSuccess: "Registration successful, please check your email to verify your account.",
  emailSent: "Verification email sent. Please check your inbox.",
  emailVerified: "Email Verified Successfully",
  loginSuccess: "Login Successfully",
  logoutSuccess: "Logout Successfully",
  resetPassword: "Reset password successful",
  forgotPassword: "Forgot password successful",
  logoutAll: "Logout all sessions successful",
  deleteSession: "Delete session successful",
  changePassword: "Change password successful",
  getSessions: "Get sessions successful",
  getProfile: "Get profile successful",
  fileUploadSuccess: "File uploaded successfully",
  fileDeleteSuccess: "File deleted successfully",
  filesUploadSuccess: "Files uploaded successfully",
  updateAvatar: "Avatar updated successfully",
  updateProfile: "Profile updated successfully",
  createPost: "Post created successfully",
  deletePost: "Post deleted successfully",
  createComment: "Comment created successfully",
  deleteComment: "Comment deleted successfully",
  followUser: "Followed user successfully",
  unfollowUser: "Unfollowed user successfully",
  searchUsers: "Search users successfully",
  getPosts: "Get posts successfully",
  likePost: "Post liked successfully",
  unlikePost: "Post unliked successfully",
  updatePost: "Post updated successfully",
  getComments: "Comments retrieved successfully",
  getFollowers: "Followers retrieved successfully",
  getFollowings: "Followings retrieved successfully",
  editComment: "Comment Edited Successfully",
  likeComment: "Comment liked successfully",
  unlikeComment: "Comment unliked successfully",
  getPostById: "Get post successfully",
};

export default successMessages;
