const successMessages = {
  // auth
  registerSuccess: "Registration successful, please check your email to verify your account.",
  emailSent: "Verification email sent. Please check your inbox.",
  emailVerified: "Email verified successfully",
  loginSuccess: "Login successful",
  logoutSuccess: "Logout successful",
  resetPassword: "Reset password successful",
  forgotPassword: "Forgot password successful",
  logoutAll: "Logout all sessions successful",
  deleteSession: "Delete session successful",
  changePassword: "Change password successful",
  getSessions: "Get sessions successful",
  getProfile: "Get profile successful",
  fileUploadSuccess: "File uploaded successfully",
  fileDeleteSuccess: "File deleted successfully",
  filesUploadSuccess: "Files uploaded successfully",
  updateAvatar: "Avatar updated successfully",
  updateProfile: "Profile updated successfully",
  createPost: "Post created successfully",
  deletePost: "Post deleted successfully",
  createComment: "Comment created successfully",
  deleteComment: "Comment deleted successfully",
  followUser: "Followed user successfully",
  unfollowUser: "Unfollowed user successfully",
  searchUsers: "Search users successfully",
  getPosts: "Get posts successfully",
  likePost: "Post liked successfully",
  unlikePost: "Post unliked successfully",
  updatePost: "Post updated successfully",
};

export default successMessages;
